import React from 'react';
import { motion } from 'framer-motion';
import { Gamepad2 } from 'lucide-react';

const Games = () => {
    return (
        <div className="container mx-auto px-6 py-12">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center max-w-3xl mx-auto"
            >
                <div className="bg-purple-100 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6 text-purple-600">
                    <Gamepad2 size={40} />
                </div>
                <h1 className="text-4xl font-bold text-gray-900 mb-6">Safety Games</h1>
                <p className="text-[14px] text-gray-600 mb-8">
                    Interactive challenges that teach safety rules through play.
                    Get ready to learn while having fun!
                </p>
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {/* AI Platformer Game */}
                    <motion.a
                        href="/src/pages/Games/AIplatformer/index.html"
                        target="_blank"
                        rel="noopener noreferrer"
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        whileHover={{ scale: 1.05, y: -5 }}
                        transition={{ duration: 0.3 }}
                        className="relative group block"
                    >
                        <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-purple-500 via-pink-500 to-red-500 p-[3px]">
                            <div className="relative bg-white dark:bg-gray-900 rounded-2xl p-6 h-full">


                                {/* Game Icon */}
                                <div className="w-16 h-16 bg-gradient-to-br from-purple-400 to-pink-600 rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform shadow-lg">
                                    <span className="text-4xl leading-none select-none filter drop-shadow-md">🎮</span>
                                </div>

                                {/* Game Title */}
                                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                                    AI Platformer
                                </h3>

                                {/* Description */}
                                <p className="text-gray-600 dark:text-gray-300 text-sm mb-4">
                                    Every level is uniquely generated by AI based on your chosen theme.
                                    Progressive difficulty with 8 stunning themes!
                                </p>

                                {/* Features */}
                                <div className="flex flex-wrap gap-2 mb-4">
                                    <span className="text-xs bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300 px-2 py-1 rounded-full">
                                        🌲 8 Themes
                                    </span>
                                    <span className="text-xs bg-pink-100 dark:bg-pink-900 text-pink-700 dark:text-pink-300 px-2 py-1 rounded-full">
                                        ⚡ Dynamic Levels
                                    </span>
                                    <span className="text-xs bg-orange-100 dark:bg-orange-900 text-orange-700 dark:text-orange-300 px-2 py-1 rounded-full">
                                        🎯 Progressive
                                    </span>
                                </div>

                                {/* Play Button */}
                                <div className="flex items-center text-purple-600 dark:text-purple-400 font-semibold group-hover:translate-x-2 transition-transform">
                                    Play Now
                                    <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                                    </svg>
                                </div>
                            </div>
                        </div>
                    </motion.a>

                    {/* AI Puzzle Game (Fuzzle) */}
                    <motion.a
                        href="/src/pages/Games/AIPuzzle/index.html"
                        target="_blank"
                        rel="noopener noreferrer"
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        whileHover={{ scale: 1.05, y: -5 }}
                        transition={{ duration: 0.3, delay: 0.1 }}
                        className="relative group block"
                    >
                        <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-cyan-500 via-blue-500 to-indigo-500 p-[3px]">
                            <div className="relative bg-white dark:bg-gray-900 rounded-2xl p-6 h-full">
                                {/* Fuzzle Badge */}
                                <div className="absolute top-4 right-4 bg-gradient-to-r from-pink-500 to-purple-500 text-white text-xs font-bold px-3 py-1 rounded-full shadow-lg animate-pulse">
                                    ✨ FUZZLE MODE
                                </div>

                                {/* Game Icon */}
                                <div className="w-16 h-16 bg-gradient-to-br from-cyan-400 to-blue-600 rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition-transform shadow-lg">
                                    <span className="text-4xl leading-none select-none filter drop-shadow-md">🧩</span>
                                </div>

                                {/* Game Title */}
                                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">
                                    AI Puzzle
                                </h3>

                                {/* Description */}
                                <p className="text-gray-600 dark:text-gray-300 text-sm mb-4">
                                    Solve logic puzzles designed by AI. Activate <strong>Fuzzle Mode</strong> for dynamic, shifting rules that challenge your mind!
                                </p>

                                {/* Features */}
                                <div className="flex flex-wrap gap-2 mb-4">
                                    <span className="text-xs bg-cyan-100 dark:bg-cyan-900 text-cyan-700 dark:text-cyan-300 px-2 py-1 rounded-full">
                                        🧠 Logic
                                    </span>
                                    <span className="text-xs bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300 px-2 py-1 rounded-full">
                                        🎲 Dynamic Rules
                                    </span>
                                    <span className="text-xs bg-pink-100 dark:bg-pink-900 text-pink-700 dark:text-pink-300 px-2 py-1 rounded-full">
                                        🎨 AI Design
                                    </span>
                                </div>

                                {/* Play Button */}
                                <div className="flex items-center text-cyan-600 dark:text-cyan-400 font-semibold group-hover:translate-x-2 transition-transform">
                                    Play Now
                                    <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
                                    </svg>
                                </div>
                            </div>
                        </div>
                    </motion.a>
                </div>

            </motion.div>
        </div>
    );
};

export default Games;
